### PR TITLE
feat: add sexinsex extension

### PR DESCRIPTION
**Pull request by justagoodman**
feat: add sexinsex extension

### CODE REVIEW

**Comment by kazemcodes** [comment]
Thanks for your contribution

**Comment by kazemcodes** [comment]
please change the extension id to "39" from "34" and I will merge it

**Comment by kazemcodes** [comment]
> please change the extension id to "39" from "34" and I will merge it

I update it myself

**Comment by kazemcodes** [comment]
thanks

**Comment by justagoodman** [comment]
because i found that unit tests are really helpful when developing this extension

**Comment by kazemcodes** [comment]
I also thought of same thing recently, I will try to make global one unit test if possible, there are some restrictions in android which prevents unit testing as sources needs context which is not available in unit testing, which means I need a little more things to make it work

**Pull request merged**
